name: kort_jomnorng_dai_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  khmer_fonts: ^0.0.6
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  khmer_chhankitek: ^0.0.4
  mobile_scanner: ^5.1.1
  dio: ^5.4.3+1
  quickalert: ^1.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/background/
    - assets/icons/
